stages:
  - packages
  - restore
  - build

packages:
 stage: 'packages'
 script:
 - 'cd src/Dkbe.CaptivePortal.MockServer && bower install'

restore:
  stage: 'restore'
  script:
  - 'dotnet restore'

build:
 stage: build
 script:
  - 'dotnet build -c Release --version-suffix %CI_BUILD_ID%'
