stages:
  - restore
  - build

restore:
 stage: 'restore'
 script:
 - 'cd src/Dkbe.CaptivePortal.MockServer && bower install'

build:
 stage: build
 script:
  - 'dotnet build -c Release --version-suffix %CI_BUILD_ID%'
