stages:
  - prepare
  - restore
  - build

prepare:
 stage: 'prepare'
 script: 
  - 'cd src/Dkbe.CaptivePortal.MockServer && npm install && bower install'

restore:
 stage: 'restore'
 script:
 - 'dotnet restore'

build:
 stage: build
 script:
  - 'cd src/Dkbe.CaptivePortal.MockServer && dotnet build -c Release --version-suffix %CI_BUILD_ID%'

