stages:
  - bower
  - build
before_script:
  - 'dotnet restore'

bower:
 stage: bower
 script:
 - 'npm install bower -g'

build:
 stage: build
 script:
  - 'cd src/Dkbe.CaptivePortal.MockServer && dotnet build -c Release --version-suffix %CI_BUILD_ID%'
